services:
  postgres:
    container_name: postgres-sql-wca
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: webchat_app_db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - webchat-app
    restart: unless-stopped
  keycloak:
    container_name: keycloak-wca
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - webchat-app
    command:
    - "start-dev" 


networks:
  webchat-app:
    driver: bridge
  



volumes:
  postgres:
    driver: local